///////////////////////////////////////////////////////////////////////////////
// ADSserverInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ADSserverServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
