///////////////////////////////////////////////////////////////////////////////
// Ikusi_module.h
#pragma once

#include "ADSserverInterfaces.h"
#include "ikusi.h"


class CIkusi_module 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_ADSserverCIkusi_module)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CIkusi_module();
	virtual	~CIkusi_module();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	Ikusi_moduleParameter m_Parameter;
	Ikusi_moduleInputs m_Inputs;
	Ikusi_moduleOutputs m_Outputs;
	Ikusi_moduleikusiDataOUT m_ikusiDataOUT;
	Ikusi_moduleCAN m_CAN;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// TODO: Custom variable
	UINT m_counter;
	ikusi Telecommande;
};
